version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
